### PR TITLE
Backoffice login form fix. closes #14

### LINKED ISSUE #14: Login form
Current template system needs to implement the actual log in to the backoffice page following the new template.
login

### PR DESCRIPTION
**Pull request by Nosk14**

### CODE REVIEW

**Review by pablo-grande — CHANGES_REQUESTED** [review]
## View
There is an incorrect relation between `<input id=...` and `<label for=...`
In a nutshell it should be something like:
```
<input id="password"
<label for="password"
```
A paired relation between `for` and `id` should exist: https://www.w3.org/TR/WCAG20-TECHS/H44.html

Also, I think this PR should include proper styling, the form is not centered and appears at the leftmost side of the screen.

## Behaviour
Yes, it does a log in but I believe it should also tell you what happens if you put incorrect information at the form, maybe use the error classes of Material Design for textfields: https://www.tutorialspoint.com/materialdesignlite/materialdesignlite_textfields.htm

And a new issue has emerged with this PR. The backoffice/ url no longer exists:

Here we can see a 404 error which is incorrect because backoffice/ exists as a home page. If you are not logged and access to backoffice/ it should redirect to backoffice/login.
 
Moreover, the new "home" url is backoffice/login and it looks like this for me:
log
See the blue bar? That's the login form behind the left nav section. And I'm logged :weary:

**Comment by pablo-grande** [comment]
Also, why is this a hotfix?

**Comment by Nosk14** [comment]
This is a hotfix because we had a form in the backoffice branch taht does not work. Actually I understand that maybe it is not a hotfix, but maybe yes. :smiley:

**Comment by Nosk14** [comment]
@pabloriutort 

> And a new issue has emerged with this PR. The backoffice/ url no longer exists:
> 404
> Here we can see a 404 error which is incorrect because backoffice/ exists as a home page. If you are not logged and access to backoffice/ it should redirect to backoffice/login.

It is not a 'new issue' because the `backoffice/` url has never existed, it has always been `backoffice/home`

**Review by pablo-grande — APPROVED** [review]

**Pull request merged**
