### PR TITLE
Create new app 'api'

### PR DESCRIPTION
**Pull request by pablo-grande**
Register new app in backend/settings.py
Ignore automatically created database
Modify upfront admin.py to register all new app models
Create a models proposal in models.py

### CODE REVIEW

**Review by Nosk14 — APPROVED** [review]
I agree with the models as a first approach and the general structure of the project looks good to me. :dog:

**Review by Nosk14 — DISMISSED** [review]

**Review by marc-ferrer — APPROVED** [review]
The models look alright. I don't have any Django-specific comments, given my knowledge of it.

**Comment by Nosk14** [comment]
https://github.com/petconnection/backend/blob/0ef5761fa17a62e2cf16eb359439362588def71b/api/models.py#L29-L30

**Comment by Nosk14** [comment]
https://github.com/petconnection/backend/blob/0ef5761fa17a62e2cf16eb359439362588def71b/api/models.py#L29-L30

I think the values of these fields should be stored in a separate table and the fields should be foreign keys of that table. This is because we need to know all possible values regardless of we have any object using these values. In addition, it will be easiest for the frontend to make a drop-down with that values and show them to the user, 

On the other hand, maybe we can rename of the fields to something like category and subcategory or classification and subclassification just because these names imply a hierarchy that actually we will have. ( and I don't really like the underscore :innocent:)

**Review by Nosk14 — APPROVED** [review]

**Pull request merged**
